### ISSUE TITLE
Problem using Http in node with debug node

### ISSUE THREAD

**Issue by ymedlop** [atellezr/node-red-contrib-log4nr#3]
Hi,

![proof](https://user-images.githubusercontent.com/5522922/51459801-f7e84500-1d59-11e9-8f3b-b35b89741ca7.png)

If we using a http in node with output to a debugger node it going to produce this error.

`21 Jan 08:47:57 - [warn] [http in:c8d8c9d0.e0ac98] TypeError: Cannot read property 'originalUrl' of undefined`

Could you add more error handling to avoid broken the request execution ?

**Comment by atellezr** [comment]
The problem was produced due to the different call to the _metric_ method from the _send_ method. Check the related node-red issue for more detail about that

Anyway, it's solved in the released version 1.0.2, since it has been added a try-catch for retrieving each data. Although if it's not changed in node-red, there could be several situations (output with more than 1 wire) with a lack of functionality in this package
